version: '3'
services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_NAME_CONTROLLER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    command: ["sh", "-c", "/opt/kafka/bin/kafka-storage.sh format --config /opt/kafka/config/kraft/server.properties --cluster-id $(/opt/kafka/bin/kafka-storage.sh random-uuid) && /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties"]
    networks:
      - kafka_net

  kafka-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-cli
    depends_on:
      - kafka
    networks:
      - kafka_net
    environment:
      KAFKA: kafka:9092
    stdin_open: true

networks:
  kafka_net:
    driver: bridge
